"""Prompt templates for research-desk agents."""

from .desk import (
    ARCHITECT_SYSTEM,
    ARCHITECT_USER,
    AUDITOR_SYSTEM,
    AUDITOR_USER,
    INDUSTRY_MACRO_SYSTEM,
    INDUSTRY_MACRO_USER,
    OPERATIONS_SYSTEM,
    OPERATIONS_USER,
    QUALITATIVE_SYSTEM,
    REVIEWER_SYSTEM,
    REVIEWER_USER,
    WRITER_SYSTEM,
    WRITER_USER,
)

__all__ = [
    "ARCHITECT_SYSTEM",
    "ARCHITECT_USER",
    "AUDITOR_SYSTEM",
    "AUDITOR_USER",
    "INDUSTRY_MACRO_SYSTEM",
    "INDUSTRY_MACRO_USER",
    "OPERATIONS_SYSTEM",
    "OPERATIONS_USER",
    "QUALITATIVE_SYSTEM",
    "REVIEWER_SYSTEM",
    "REVIEWER_USER",
    "WRITER_SYSTEM",
    "WRITER_USER",
]
